server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
spring:
  application:
    name: EurekaServer
  zipkin:
    base-url: http://localhost:9411
management:
  tracing:
    sampling:
      probability: 1.0