server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
spring:
  application:
    name: EurekaServer
management:
  tracing:
    sampling:
      probability: 1.0
#  zipkin:
#    tracing:
#      endpoint: http://localhost:9411